name: Release
description: Releases to an APT repository

runs:
  using: composite
  steps:
  - uses: ./.github/actions/install-dependencies
  - name: Build
    run: python -m debutizer build --package-dir tests/resources/local_upstreams
    shell: bash
