name: Release
description: Releases to an APT repository

inputs:
  config_file:
    description: The Debutizer configuration file to use
    required: false
    default: debutizer.yaml

runs:
  using: composite
  steps:
  - uses: ./.github/actions/install-dependencies
  - name: Build
    run: >
      python -m debutizer build
      --package-dir tests/resources/local_upstreams
      --config-file ${{ inputs.config_file }}
    shell: bash
