name: Install Dependencies
description: Installs system and Python dependencies for Debutizer

runs:
  using: composite
  steps:
  - uses: actions/setup-python@v2
    with:
      python-version: '3.8'
  - name: Install system dependencies
    run: sudo apt-get update && sudo apt-get install pbuilder devscripts quilt debian-keyring s3fs
    shell: bash
  - name: Install Python dependencies
    run: python -m pip install ".[dev]"
    shell: bash
