# Configures linting tools to run before developers commit their code.

# The pre-commit tool is designed install tools for you, ensuring they're
# always available. However, we rely on Poetry to install our tools instead, so
# we bypass this feature by defining our own custom hooks.

fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --check --dont-follow-links .
        require_serial: true
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check .
        require_serial: true
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy -p debutizer
        require_serial: true
        pass_filenames: false
        language: system
