name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install ".[dev]"
      - run: isort --check --dont-follow-links .
      - run: black --check .
      - run: mypy -p debutizer
