name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
      - name: Run isort
        run: isort --check --dont-follow-links .
      - name: Run black
        run: black --check .
      - name: Run MyPy
        run: mypy -p debutizer
