name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: python -m pip install ".[dev]"
      - name: Run isort
        run: isort --check --dont-follow-links .
      - name: Run black
        run: black --check .
      - name: Run MyPy
        run: mypy -p debutizer
