name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
      - name: Install Python dependencies
        # This is done with sudo so that packages are installed system-wide. This
        # allows Pip to skip packages that are already installed via apt.
        run: sudo pip3 install ".[dev]"
        shell: bash
      - name: Run isort
        run: isort --check --dont-follow-links .
      - name: Run black
        run: black --check .
      - name: Run MyPy
        run: mypy --strict -p debutizer
