name: Production Release

on:
  release:
    types:
      - created

jobs:
  build-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
      - name: Build APT Packages
        run: python -m debutizer build --package-dir tests/resources/local_upstreams
      - name: Upload APT Packages
        run: python -m debutizer s3-repo upload --profile prod
        env:
          DEBUTIZER_ACCESS_KEY: ${{ secrets.PROD_ACCESS_KEY }}
          DEBUTIZER_SECRET_KEY: ${{ secrets.PROD_SECRET_KEY }}
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  pypi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pypi-release
        name: Release to PyPI
        with:
          repository_url: https://upload.pypi.org/legacy/
          api_token: ${{ secrets.PYPI_API_TOKEN }}
