name: Production Release

on:
  release:
    types:
      - created

jobs:
  build-packages:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distribution: [ 'bionic', 'focal', 'hirsute' ]
    steps:
      - uses: actions/checkout@v2
      - name: Write Configuration
        run: |
          cat << EOF > debutizer.yaml
          distribution: '${{ matrix.distribution }}'
          upstream_repo: http://apt.debutizer.dev
          upstream_components: [main]
          upstream_is_trusted: true
          EOF
        shell: bash
      - uses: ./.github/actions/apt-build
        name: Build APT Package
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.distribution }}
          path: artifacts/dists/${{ matrix.distribution }}
  upload-packages:
    needs: build-packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: bionic
          path: artifacts/dists/bionic
      - uses: actions/download-artifact@v2
        with:
          name: focal
          path: artifacts/dists/focal
      - uses: actions/download-artifact@v2
        with:
          name: hirsute
          path: artifacts/dists/hirsute
      - name: Write Configuration
        run: |
          cat << EOF > debutizer.yaml
          distribution: '${{ matrix.distribution }}'
          s3_repo:
            endpoint: https://storage.googleapis.com
            bucket: apt-debutizer-dev
            cache_control: no-cache
            sign: true
          EOF
        shell: bash
      - uses: ./.github/actions/apt-upload
        name: Upload APT Packages
        env:
          DEBUTIZER_ACCESS_KEY: ${{ secrets.PROD_ACCESS_KEY }}
          DEBUTIZER_SECRET_KEY: ${{ secrets.PROD_SECRET_KEY }}
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  pypi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pypi-release
        name: Release to PyPI
        with:
          repository_url: https://upload.pypi.org/legacy/
          api_token: ${{ secrets.PYPI_API_TOKEN }}
