name: Production Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distribution: [ 'bionic', 'focal', 'hirsute' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/release
        with:
          distribution: ${{ matrix.distribution }}
          upstream_repo: http://apt.debutizer.dev
          bucket_name: apt-debutizer-dev
          access_key: ${{ secrets.PROD_ACCESS_KEY }}
          secret_key: ${{ secrets.PROD_SECRET_KEY }}
