name: Staging Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distribution: ['bionic', 'focal', 'hirsute']
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/release
        with:
          distribution: ${{ matrix.distribution }}
          bucket_name: apt-staging-debutizer-dev
          access_key: ${{ secrets.STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.STAGING_SECRET_KEY }}
