name: Staging Release

on:
  push:
    branches:
      - feature/6-s3-upload

jobs:
  bionic:
    uses: velovix/debutizer/release.yaml@feature/6-s3-upload
    with:
      distribution: bionic
      bucket_name: apt-staging-debutizer-dev
    secrets:
      access_key: ${{ secrets.ACCESS_KEY }}
      secret_key: ${{ secrets.SECRET_KEY }}
  focal:
    uses: velovix/debutizer/release.yaml@feature/6-s3-upload
    with:
      distribution: cocal
      bucket_name: apt-staging-debutizer-dev
    secrets:
      access_key: ${{ secrets.ACCESS_KEY }}
      secret_key: ${{ secrets.SECRET_KEY }}
