name: Staging Release

on:
  push:
    branches:
      - main
      - feature/20-deploy-to-pypi

jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distribution: [ 'bionic', 'focal', 'hirsute' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/apt-release
        name: Release to APT Repository
        with:
          distribution: ${{ matrix.distribution }}
          # We check against the production repo so that new packages will be
          # rebuilt for every new commit before being introduced to production,
          # making development easier.
          upstream_repo: http://apt.debutizer.dev
          bucket_name: apt-staging-debutizer-dev
          access_key: ${{ secrets.STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.STAGING_SECRET_KEY }}
          # Since we re-upload the same version of the package multiple times
          cache_control: no-cache
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - uses: ./.github/actions/pypi-release
        name: Release to Test PyPI
        with:
          repository_url: https://test.pypi.org/legacy/
          api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
