name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
        with:
          python_version: "3.6"
      - name: Run tests
        run: pytest .
