name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
      - name: Install Python dependencies
        # This is done with sudo so that packages are installed system-wide. This
        # allows Pip to skip packages that are already installed via apt.
        run: sudo pip3 install --constraint constraints.txt ".[dev]"
        shell: bash
      - name: Give Cache Access to Chroots
        shell: bash
        run: |
          sudo mkdir -p /var/cache/pbuilder
          sudo chown $(whoami) /var/cache/pbuilder
      - name: Cache Chroots
        uses: actions/cache@v2
        with:
          path: /var/cache/pbuilder/debutizer-*.tgz
          key: chroots-v4
      - name: Run tests
        run: pytest --capture=no --verbose .
        env:
          # Using sudo to selectively get root permissions works well in CI,
          # since sudo is configured to be password-less
          DEBUTIZER_ACQUIRE_ROOT: "1"
