name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install system dependencies
        run: sudo apt-get install pbuilder devscripts quilt debian-keyring
      - name: Install Python dependencies
        run: python -m pip install ".[dev]"
      - name: Run tests
        run: pytest .
